// Expected: Before throw
// Expected: Caught exception
// Expected: Finally block executed  
// Expected: Program continues
// Test basic exception handling
func int main() {
    try {
        Console.WriteLine("Before throw");
        throw "Something went wrong!";
        Console.WriteLine("This should not print");
    } catch (Exception e) {
        Console.WriteLine("Caught exception");
    } finally {
        Console.WriteLine("Finally block executed");
    }
    
    Console.WriteLine("Program continues");
    return 0;
}